### PR TITLE
Added #where to base.rb

### PR DESCRIPTION
**Pull request by dhruvasagar**
Added a basic implementation of #where to base.rb, filters by all the given keys doing an effective sql 'AND' for all. Each key can have a single or multiple (Array) values, in case it's single it's simple, in case it's multiple, it will look for all values.

Simplified example of how it should work :

``` ruby
Model.where(:id => [1,2]) #=> [#<Model ID=1...>, #<Model ID=2...>]
Model.where(:id => 1, :name => 'test') #=> [#<Model ID=1 NAME='test'...>]
```

### CODE REVIEW

**Comment by jpwynn** [comment]
+1

**Comment by springbok** [comment]
+1

**Comment by dhruvasagar** [comment]
Awesome

**Comment by dhruvasagar** [comment]
Hi, I don't believe these changes have been published to rubygems

**Pull request merged**
