### PR TITLE
Relax pinned rails dependencies so that gem works with all 3.x and above rails versions 

### PR DESCRIPTION
**Pull request by quarklemotion**

### CODE REVIEW

**Comment by jeffshantz** [comment]
+1   Without this, `supermodel` is pretty well useless right now for me.  For instance, I am using `appraisal` to test my gem against Rails 3.0.x, 3.1.x, 3.2.x, and 4.0.0.rc1.  Due to the `activemodel` dependency in this gem, I can't use `supermodel`.

**Comment by maccman** [comment]
Done! Sorry for the delay!

**Comment by jeffshantz** [comment]
Thank you! :+1: :)

**Comment by adamwong246** [comment]
I might just be ignorant but- Why do I see version 0.1.6 on https://rubygems.org/gems/supermodel? Shouldn't it be 0.1.7?

**Comment by quarklemotion** [comment]
The latest version hasn't been pushed to rubygems - I've just been using a gihub URL in my gemfile to grab the latest.  @maccman when you get a chance can you push v0.1.7 to rubygems?

**Pull request merged**
